# Generated by Django 4.2.23 on 2025-08-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathologist', '0002_pathologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
