# Generated by Django 5.2.4 on 2025-08-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathologist', '0003_alter_pathologist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='patient',
            new_name='report_id',
        ),
    ]
