# Generated by Django 4.2.23 on 2025-08-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
