# Generated by Django 4.2.23 on 2025-08-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_delete_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
